# Class 5/12
## Setting Up Tensor Flow and Neural Networks
### Dirks Wright

In [ ]:
### set up new environment
import venv
venv.create('.venv', with_pip=True)

In [3]:
### switch to the virtual environment
import subprocess
import sys
from pathlib import Path

venv_python = Path(".venv/Scripts/python.exe")

subprocess.check_call([venv_python, "-m", "pip", "install", "tensorflow", "ipykernel"])

0

In [4]:
### register new kernel
subprocess.check_call([
    venv_python, "-m", "ipykernel", "install",
    "--user",
    "--name=tf-env",
    "--display-name=Python (tf-env)"
])

0

In [1]:
### install tensor flow
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (7.34.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (2.34.0)
Requirement already satisfied: setuptools in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (82.0.1)
Requirement already satisfied: six>=1.12.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (3.14.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (2.4.4)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.14)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
### install required packages
!pip install pandas numpy scikit-learn

Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (2.4.4)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 2.4 MB/s eta 0:00:04
   ----- ---------------------------------- 1.3/9.8 MB 3.2 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.8 MB 3.6 MB/s eta 0:00:03
   ----------- ---------------------------- 2.9/9.8 MB 3.6 MB/s eta 0:00:02
   ---------------- ----------------------- 3.9/9.8 MB 3.9 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.8 MB 4.5 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.8 MB 4.1 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.8 MB 4.0 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.8 MB 3.6 MB/s eta 0:00:01
   --------------------------------- ------ 8.1/9.8 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 4.2 MB/s eta 0:00:00
Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   --------------- ------------------------ 3.1/8.0 MB 14.6 MB/s eta 0:00:01
   --------------------------- ------------ 5.5/8.0 MB 13.0 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 13.2 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 11.7 MB/s eta 0:00:00
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   -- ------------------------------------- 2.4/36.5 MB 11.1 MB/s eta 0:00:04
   ---- ----------------------------------- 4.5/36.5 MB 10.9 MB/s eta 0:00:03
   -------- ------------------------------- 7.3/36.5 MB 11.3 MB/s eta 0:00:03
   ----------- ---------------------------- 10.5/36.5 MB 12.5 MB/s eta 0:00:03
   --------------- ------------------------ 14.2/36.5 MB 13.5 MB/s eta 0:00:02
   ------------------ --------------------- 17.3/36.5 MB 13.7 MB/s eta 0:00:02
   ---------------------- ----------------- 20.4/36.5 MB 14.0 MB/s eta 0:00:02
   ------------------------ --------------- 22.8/36.5 MB 13.5 MB/s eta 0:00:02
   --------------------------- ------------ 24.9/36.5 MB 13.2 MB/s eta 0:00:01
   ----------------------------- ---------- 27.3/36.5 MB 12.9 MB/s eta 0:00:01
   -------------------------------- ------- 29.9/36.5 MB 12.9 MB/s eta 0:00:01
   ----------------------------------- ---- 32.2/36.5 MB 12.7 MB/s eta 0:00:01
   ------------------------------------- -- 34.6/36.5 MB 12.6 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 12.5 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 11.7 MB/s eta 0:00:00
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, threadpoolctl, scipy, joblib, scikit-learn, pandas

   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ---------------------------------------- 0/6 [tzdata]
   ------ --------------------------------- 1/6 [threadpoolctl]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   ------------- -------------------------- 2/6 [scipy]
   -------------------- ------------------- 3/6 [joblib]

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [3]:
! pip install palmerpenguins
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()

Requirement already satisfied: palmerpenguins in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (0.1.6)
Requirement already satisfied: pandas in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from palmerpenguins) (3.0.3)
Requirement already satisfied: numpy in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from palmerpenguins) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from pandas->palmerpenguins) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\dirks wright\onedrive\documents\advanced machine\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [4]:
### drop nan rows
penguins = penguins.dropna()
penguins.shape

(333, 8)

In [5]:
### shuffle the data
penguins = penguins.sample(frac = 1, random_state = 42).reset_index(drop=True)

In [6]:
penguins_x = pd.concat(
    [
        penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']],
        pd.get_dummies(penguins['sex'], dtype=int)
    ],
    axis=1
).astype(float)
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,3250.0,39.5,16.7,178.0,1.0,0.0
1,3675.0,50.9,17.9,196.0,1.0,0.0
2,4000.0,42.1,19.1,195.0,0.0,1.0
3,4850.0,46.6,14.2,210.0,1.0,0.0
4,4050.0,41.1,18.2,192.0,0.0,1.0
...,...,...,...,...,...,...
328,4750.0,49.6,15.0,216.0,0.0,1.0
329,3900.0,37.2,19.4,184.0,0.0,1.0
330,3200.0,39.7,17.7,193.0,1.0,0.0
331,3950.0,45.2,17.8,198.0,1.0,0.0
332,3175.0,38.1,17.0,181.0,1.0,0.0

In [7]:
penguins_y = penguins['species'].astype('category').cat.codes.to_numpy()

X_train, X_val, y_train, y_val = train_test_split(
    penguins_x,
    penguins_y,
    test_size=0.2,
    random_state=42,
    stratify=penguins_y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

X_train_scaled.shape, X_val_scaled.shape

((266, 6), (67, 6))

In [8]:
pd.DataFrame({
    'train_count': pd.Series(y_train).value_counts().sort_index(),
    'validation_count': pd.Series(y_val).value_counts().sort_index()
})

   train_count  validation_count
0          117                29
1           54                14
2           95                24

In [9]:
#construct the model
inputs = keras.Input(shape=(X_train_scaled.shape[1],))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [10]:
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [11]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(
    X_train_scaled,
    y_train,
    batch_size=64,
    epochs=100,
    validation_data=(X_val_scaled, y_val)
)

scores = model.evaluate(X_val_scaled, y_val, verbose=2)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.5639 - loss: 1.0931 - val_accuracy: 0.5821 - val_loss: 1.0814
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5752 - loss: 1.0820 - val_accuracy: 0.5821 - val_loss: 1.0716
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5789 - loss: 1.0732 - val_accuracy: 0.5821 - val_loss: 1.0630
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5789 - loss: 1.0652 - val_accuracy: 0.5821 - val_loss: 1.0553
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5789 - loss: 1.0577 - val_accuracy: 0.5821 - val_loss: 1.0469
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5977 - loss: 1.0490 - val_accuracy: 0.5821 - val_loss: 1.0373
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6015 - loss: 1.0394 - val_accuracy: 0.5821 - val_loss: 1.0281
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6053 - loss: 1.0300 - val_accuracy: 0.5821 - val_loss: 1.0179
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6053 - loss: 1.0198 - val_accuracy: 0.5821 - val_loss: 1.0087
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6128 - loss: 1.0100 - val_accuracy: 0.5970 - val_loss: 1.0009
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6165 - loss: 1.0013 - val_accuracy: 0.5970 - val_loss: 0.9908
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6353 - loss: 0.9902 - val_accuracy: 0.6119 - val_loss: 0.9818
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6353 - loss: 0.9804 - val_accuracy: 0.6119 - val_loss: 0.9723
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6353 - loss: 0.9700 - val_accuracy: 0.6119 - val_loss: 0.9616
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6391 - loss: 0.9584 - val_accuracy: 0.6119 - val_loss: 0.9503
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6579 - loss: 0.9466 - val_accuracy: 0.6269 - val_loss: 0.9404
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6729 - loss: 0.9362 - val_accuracy: 0.6269 - val_loss: 0.9303
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6805 - loss: 0.9257 - val_accuracy: 0.6418 - val_loss: 0.9202
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6917 - loss: 0.9152 - val_accuracy: 0.6269 - val_loss: 0.9089
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7105 - loss: 0.9029 - val_accuracy: 0.6716 - val_loss: 0.8994
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7293 - loss: 0.8919 - val_accuracy: 0.6716 - val_loss: 0.8890
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7444 - loss: 0.8808 - val_accuracy: 0.7164 - val_loss: 0.8778
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7594 - loss: 0.8694 - val_accuracy: 0.7761 - val_loss: 0.8664
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7932 - loss: 0.8574 - val_accuracy: 0.7761 - val_loss: 0.8549
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8308 - loss: 0.8460 - val_accuracy: 0.7761 - val_loss: 0.8453
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8496 - loss: 0.8348 - val_accuracy: 0.7761 - val_loss: 0.8352
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8609 - loss: 0.8243 - val_accuracy: 0.7761 - val_loss: 0.8242
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8684 - loss: 0.8128 - val_accuracy: 0.8060 - val_loss: 0.8137
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8647 - loss: 0.8010 - val_accuracy: 0.8060 - val_loss: 0.8028
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8684 - loss: 0.7897 - val_accuracy: 0.8209 - val_loss: 0.7926
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8722 - loss: 0.7792 - val_accuracy: 0.8060 - val_loss: 0.7824
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8647 - loss: 0.7677 - val_accuracy: 0.8060 - val_loss: 0.7738
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8684 - loss: 0.7570 - val_accuracy: 0.8060 - val_loss: 0.7635
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8684 - loss: 0.7463 - val_accuracy: 0.8209 - val_loss: 0.7535
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8684 - loss: 0.7353 - val_accuracy: 0.8358 - val_loss: 0.7439
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8684 - loss: 0.7252 - val_accuracy: 0.8358 - val_loss: 0.7345
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8684 - loss: 0.7150 - val_accuracy: 0.8358 - val_loss: 0.7245
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8722 - loss: 0.7044 - val_accuracy: 0.8358 - val_loss: 0.7156
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8722 - loss: 0.6942 - val_accuracy: 0.8358 - val_loss: 0.7064
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8759 - loss: 0.6841 - val_accuracy: 0.8358 - val_loss: 0.6974
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8684 - loss: 0.6739 - val_accuracy: 0.8358 - val_loss: 0.6887
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8759 - loss: 0.6644 - val_accuracy: 0.8507 - val_loss: 0.6799
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8759 - loss: 0.6550 - val_accuracy: 0.8507 - val_loss: 0.6713
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8684 - loss: 0.6454 - val_accuracy: 0.8507 - val_loss: 0.6633
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8759 - loss: 0.6363 - val_accuracy: 0.8507 - val_loss: 0.6556
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8722 - loss: 0.6274 - val_accuracy: 0.8507 - val_loss: 0.6473
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8684 - loss: 0.6181 - val_accuracy: 0.8507 - val_loss: 0.6390
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8722 - loss: 0.6092 - val_accuracy: 0.8507 - val_loss: 0.6314
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8759 - loss: 0.6004 - val_accuracy: 0.8507 - val_loss: 0.6239
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8835 - loss: 0.5919 - val_accuracy: 0.8507 - val_loss: 0.6170
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8835 - loss: 0.5842 - val_accuracy: 0.8507 - val_loss: 0.6099
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8872 - loss: 0.5761 - val_accuracy: 0.8507 - val_loss: 0.6025
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8872 - loss: 0.5686 - val_accuracy: 0.8507 - val_loss: 0.5959
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8947 - loss: 0.5612 - val_accuracy: 0.8507 - val_loss: 0.5888
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8872 - loss: 0.5536 - val_accuracy: 0.8507 - val_loss: 0.5821
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8872 - loss: 0.5462 - val_accuracy: 0.8507 - val_loss: 0.5757
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8947 - loss: 0.5397 - val_accuracy: 0.8507 - val_loss: 0.5691
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9060 - loss: 0.5328 - val_accuracy: 0.8507 - val_loss: 0.5632
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9023 - loss: 0.5264 - val_accuracy: 0.8507 - val_loss: 0.5572
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9135 - loss: 0.5198 - val_accuracy: 0.8507 - val_loss: 0.5505
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9098 - loss: 0.5132 - val_accuracy: 0.8507 - val_loss: 0.5445
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9173 - loss: 0.5073 - val_accuracy: 0.8507 - val_loss: 0.5390
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9173 - loss: 0.5018 - val_accuracy: 0.8806 - val_loss: 0.5334
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9286 - loss: 0.4963 - val_accuracy: 0.8806 - val_loss: 0.5279
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9286 - loss: 0.4908 - val_accuracy: 0.8955 - val_loss: 0.5214
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9361 - loss: 0.4848 - val_accuracy: 0.8955 - val_loss: 0.5156
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9323 - loss: 0.4790 - val_accuracy: 0.8955 - val_loss: 0.5100
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9323 - loss: 0.4732 - val_accuracy: 0.9104 - val_loss: 0.5036
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9361 - loss: 0.4672 - val_accuracy: 0.9104 - val_loss: 0.4985
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9361 - loss: 0.4620 - val_accuracy: 0.9104 - val_loss: 0.4932
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9398 - loss: 0.4571 - val_accuracy: 0.9104 - val_loss: 0.4880
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9436 - loss: 0.4520 - val_accuracy: 0.9104 - val_loss: 0.4824
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9474 - loss: 0.4465 - val_accuracy: 0.9254 - val_loss: 0.4768
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9511 - loss: 0.4413 - val_accuracy: 0.9254 - val_loss: 0.4719
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9511 - loss: 0.4366 - val_accuracy: 0.9254 - val_loss: 0.4668
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9549 - loss: 0.4319 - val_accuracy: 0.9254 - val_loss: 0.4616
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9586 - loss: 0.4267 - val_accuracy: 0.9254 - val_loss: 0.4569
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9586 - loss: 0.4221 - val_accuracy: 0.9403 - val_loss: 0.4518
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9586 - loss: 0.4173 - val_accuracy: 0.9403 - val_loss: 0.4464
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9586 - loss: 0.4121 - val_accuracy: 0.9403 - val_loss: 0.4409
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9624 - loss: 0.4073 - val_accuracy: 0.9403 - val_loss: 0.4354
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9662 - loss: 0.4020 - val_accuracy: 0.9403 - val_loss: 0.4302
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9662 - loss: 0.3970 - val_accuracy: 0.9403 - val_loss: 0.4256
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9699 - loss: 0.3925 - val_accuracy: 0.9403 - val_loss: 0.4213
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9737 - loss: 0.3879 - val_accuracy: 0.9552 - val_loss: 0.4161
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9737 - loss: 0.3833 - val_accuracy: 0.9552 - val_loss: 0.4115
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9737 - loss: 0.3788 - val_accuracy: 0.9552 - val_loss: 0.4072
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9774 - loss: 0.3746 - val_accuracy: 0.9552 - val_loss: 0.4021
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9774 - loss: 0.3699 - val_accuracy: 0.9552 - val_loss: 0.3980
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9774 - loss: 0.3658 - val_accuracy: 0.9552 - val_loss: 0.3932
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9812 - loss: 0.3611 - val_accuracy: 0.9552 - val_loss: 0.3884
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9812 - loss: 0.3567 - val_accuracy: 0.9552 - val_loss: 0.3843
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9812 - loss: 0.3526 - val_accuracy: 0.9552 - val_loss: 0.3798
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9812 - loss: 0.3483 - val_accuracy: 0.9552 - val_loss: 0.3748
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9812 - loss: 0.3441 - val_accuracy: 0.9552 - val_loss: 0.3702
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9812 - loss: 0.3397 - val_accuracy: 0.9552 - val_loss: 0.3668
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9812 - loss: 0.3357 - val_accuracy: 0.9552 - val_loss: 0.3627
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9812 - loss: 0.3319 - val_accuracy: 0.9552 - val_loss: 0.3580
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9812 - loss: 0.3279 - val_accuracy: 0.9552 - val_loss: 0.3534
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9850 - loss: 0.3238 - val_accuracy: 0.9552 - val_loss: 0.3493
3/3 - 0s - 11ms/step - accuracy: 0.9552 - loss: 0.3493

In [12]:
inputs_logit_true = keras.Input(shape=(X_train_scaled.shape[1],))
x_logit_true = layers.Dense(7, activation='relu')(inputs_logit_true)
x_logit_true = layers.Dense(5, activation='relu')(x_logit_true)
x_logit_true = layers.Dense(3, activation='relu')(x_logit_true)
outputs_logit_true = layers.Dense(3, activation='softmax')(x_logit_true)
model_logit_true = keras.Model(inputs=inputs_logit_true, outputs=outputs_logit_true, name="penguin_model_scaled")

model_logit_true.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_true.fit(
    X_train_scaled,
    y_train,
    batch_size=64,
    epochs=100,
    validation_data=(X_val_scaled, y_val)
)

scores = model_logit_true.evaluate(X_val_scaled, y_val, verbose=2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.2519 - loss: 1.0734 - val_accuracy: 0.2090 - val_loss: 1.0764
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.2707 - loss: 1.0481 - val_accuracy: 0.3134 - val_loss: 1.0561
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3571 - loss: 1.0278 - val_accuracy: 0.4030 - val_loss: 1.0408
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.4248 - loss: 1.0107 - val_accuracy: 0.4776 - val_loss: 1.0258
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5338 - loss: 0.9950 - val_accuracy: 0.4925 - val_loss: 1.0122
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5865 - loss: 0.9810 - val_accuracy: 0.5522 - val_loss: 0.9987
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6203 - loss: 0.9668 - val_accuracy: 0.5821 - val_loss: 0.9850
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6692 - loss: 0.9518 - val_accuracy: 0.6567 - val_loss: 0.9683
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6917 - loss: 0.9364 - val_accuracy: 0.7015 - val_loss: 0.9517
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7143 - loss: 0.9212 - val_accuracy: 0.7015 - val_loss: 0.9370
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7180 - loss: 0.9071 - val_accuracy: 0.7164 - val_loss: 0.9222
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7293 - loss: 0.8923 - val_accuracy: 0.7313 - val_loss: 0.9044
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7481 - loss: 0.8759 - val_accuracy: 0.7313 - val_loss: 0.8888
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7632 - loss: 0.8611 - val_accuracy: 0.7463 - val_loss: 0.8724
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7707 - loss: 0.8460 - val_accuracy: 0.7463 - val_loss: 0.8566
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7857 - loss: 0.8313 - val_accuracy: 0.7463 - val_loss: 0.8409
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7857 - loss: 0.8169 - val_accuracy: 0.7463 - val_loss: 0.8262
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7857 - loss: 0.8034 - val_accuracy: 0.7463 - val_loss: 0.8106
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7895 - loss: 0.7893 - val_accuracy: 0.7463 - val_loss: 0.7959
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7895 - loss: 0.7759 - val_accuracy: 0.7612 - val_loss: 0.7836
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7932 - loss: 0.7647 - val_accuracy: 0.7612 - val_loss: 0.7701
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.7524 - val_accuracy: 0.7761 - val_loss: 0.7563
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7932 - loss: 0.7396 - val_accuracy: 0.7761 - val_loss: 0.7439
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7970 - loss: 0.7282 - val_accuracy: 0.7761 - val_loss: 0.7316
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.7169 - val_accuracy: 0.7761 - val_loss: 0.7200
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.7060 - val_accuracy: 0.7761 - val_loss: 0.7088
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.6955 - val_accuracy: 0.7761 - val_loss: 0.6975
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7970 - loss: 0.6849 - val_accuracy: 0.7761 - val_loss: 0.6878
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7970 - loss: 0.6753 - val_accuracy: 0.7910 - val_loss: 0.6778
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7970 - loss: 0.6657 - val_accuracy: 0.7910 - val_loss: 0.6677
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7970 - loss: 0.6557 - val_accuracy: 0.7910 - val_loss: 0.6590
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.6470 - val_accuracy: 0.7910 - val_loss: 0.6502
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7970 - loss: 0.6380 - val_accuracy: 0.7910 - val_loss: 0.6416
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.6293 - val_accuracy: 0.7910 - val_loss: 0.6331
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7970 - loss: 0.6205 - val_accuracy: 0.7910 - val_loss: 0.6250
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7970 - loss: 0.6121 - val_accuracy: 0.7910 - val_loss: 0.6170
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7970 - loss: 0.6037 - val_accuracy: 0.7910 - val_loss: 0.6089
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7970 - loss: 0.5954 - val_accuracy: 0.7910 - val_loss: 0.6007
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.5875 - val_accuracy: 0.7910 - val_loss: 0.5929
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.5794 - val_accuracy: 0.7910 - val_loss: 0.5854
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7970 - loss: 0.5715 - val_accuracy: 0.7910 - val_loss: 0.5783
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7970 - loss: 0.5643 - val_accuracy: 0.7910 - val_loss: 0.5712
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7970 - loss: 0.5572 - val_accuracy: 0.7910 - val_loss: 0.5632
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.5494 - val_accuracy: 0.7910 - val_loss: 0.5558
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7970 - loss: 0.5424 - val_accuracy: 0.7910 - val_loss: 0.5485
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7970 - loss: 0.5358 - val_accuracy: 0.7910 - val_loss: 0.5407
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7970 - loss: 0.5283 - val_accuracy: 0.7910 - val_loss: 0.5335
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7970 - loss: 0.5213 - val_accuracy: 0.7910 - val_loss: 0.5262
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7970 - loss: 0.5142 - val_accuracy: 0.7910 - val_loss: 0.5194
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.5075 - val_accuracy: 0.7910 - val_loss: 0.5128
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.5011 - val_accuracy: 0.7910 - val_loss: 0.5058
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.4943 - val_accuracy: 0.7910 - val_loss: 0.4990
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.4876 - val_accuracy: 0.7910 - val_loss: 0.4933
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7970 - loss: 0.4818 - val_accuracy: 0.7910 - val_loss: 0.4872
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.4758 - val_accuracy: 0.7910 - val_loss: 0.4813
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.4698 - val_accuracy: 0.7910 - val_loss: 0.4749
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.4636 - val_accuracy: 0.7910 - val_loss: 0.4691
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.4578 - val_accuracy: 0.7910 - val_loss: 0.4633
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.4520 - val_accuracy: 0.7910 - val_loss: 0.4569
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.4457 - val_accuracy: 0.7910 - val_loss: 0.4512
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.4400 - val_accuracy: 0.7910 - val_loss: 0.4455
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.4343 - val_accuracy: 0.7910 - val_loss: 0.4408
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.4296 - val_accuracy: 0.7910 - val_loss: 0.4349
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.4238 - val_accuracy: 0.7910 - val_loss: 0.4301
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7970 - loss: 0.4188 - val_accuracy: 0.7910 - val_loss: 0.4242
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.4131 - val_accuracy: 0.7910 - val_loss: 0.4201
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7970 - loss: 0.4089 - val_accuracy: 0.7910 - val_loss: 0.4161
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.4047 - val_accuracy: 0.7910 - val_loss: 0.4119
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.4000 - val_accuracy: 0.7910 - val_loss: 0.4078
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.3957 - val_accuracy: 0.7910 - val_loss: 0.4032
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.3907 - val_accuracy: 0.7910 - val_loss: 0.3984
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.3855 - val_accuracy: 0.7910 - val_loss: 0.3938
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7970 - loss: 0.3806 - val_accuracy: 0.7910 - val_loss: 0.3896
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.3759 - val_accuracy: 0.7910 - val_loss: 0.3856
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.3712 - val_accuracy: 0.7910 - val_loss: 0.3814
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.3666 - val_accuracy: 0.7910 - val_loss: 0.3780
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.3627 - val_accuracy: 0.7910 - val_loss: 0.3742
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7970 - loss: 0.3583 - val_accuracy: 0.7910 - val_loss: 0.3709
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.3544 - val_accuracy: 0.7910 - val_loss: 0.3677
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.3507 - val_accuracy: 0.7910 - val_loss: 0.3644
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7970 - loss: 0.3469 - val_accuracy: 0.7910 - val_loss: 0.3612
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7970 - loss: 0.3431 - val_accuracy: 0.7910 - val_loss: 0.3576
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7970 - loss: 0.3389 - val_accuracy: 0.7910 - val_loss: 0.3543
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7970 - loss: 0.3349 - val_accuracy: 0.7910 - val_loss: 0.3508
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7970 - loss: 0.3306 - val_accuracy: 0.7910 - val_loss: 0.3477
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7970 - loss: 0.3268 - val_accuracy: 0.7910 - val_loss: 0.3447
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7970 - loss: 0.3229 - val_accuracy: 0.7910 - val_loss: 0.3416
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7970 - loss: 0.3192 - val_accuracy: 0.7910 - val_loss: 0.3388
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8045 - loss: 0.3155 - val_accuracy: 0.8060 - val_loss: 0.3360
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8083 - loss: 0.3120 - val_accuracy: 0.8060 - val_loss: 0.3334
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8083 - loss: 0.3086 - val_accuracy: 0.8060 - val_loss: 0.3308
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8120 - loss: 0.3049 - val_accuracy: 0.8060 - val_loss: 0.3280
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8120 - loss: 0.3012 - val_accuracy: 0.8060 - val_loss: 0.3254
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8195 - loss: 0.2979 - val_accuracy: 0.8060 - val_loss: 0.3226
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8195 - loss: 0.2949 - val_accuracy: 0.7910 - val_loss: 0.3201
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8233 - loss: 0.2913 - val_accuracy: 0.7910 - val_loss: 0.3179
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8195 - loss: 0.2882 - val_accuracy: 0.7910 - val_loss: 0.3152
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8271 - loss: 0.2849 - val_accuracy: 0.7910 - val_loss: 0.3127
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8383 - loss: 0.2819 - val_accuracy: 0.7910 - val_loss: 0.3099
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8421 - loss: 0.2785 - val_accuracy: 0.8060 - val_loss: 0.3065
3/3 - 0s - 11ms/step - accuracy: 0.8060 - loss: 0.3065

In [13]:
model_logit_true.predict(X_val_scaled)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

array([[4.94092660e-07, 7.48484745e-04, 9.99251068e-01],
       [4.42439467e-01, 3.55196834e-01, 2.02363729e-01],
       [7.65357554e-01, 2.08587408e-01, 2.60550659e-02],
       [2.31833184e-07, 5.04514668e-04, 9.99495268e-01],
       [2.50685996e-08, 1.71554027e-04, 9.99828458e-01],
       [1.75563613e-07, 4.39495430e-04, 9.99560416e-01],
       [7.86062837e-01, 1.93076372e-01, 2.08608638e-02],
       [8.79761636e-01, 1.14760429e-01, 5.47801610e-03],
       [8.77149880e-01, 1.17079020e-01, 5.77110238e-03],
       [5.39321604e-07, 7.78975722e-04, 9.99220371e-01],
       [3.75187069e-01, 3.62607926e-01, 2.62205034e-01],
       [8.99898469e-01, 9.65908617e-02, 3.51062510e-03],
       [9.20743763e-01, 7.72655755e-02, 1.99068571e-03],
       [6.75447464e-01, 2.65382260e-01, 5.91703318e-02],
       [6.09031856e-01, 2.99545735e-01, 9.14224312e-02],
       [9.23420727e-01, 7.47480243e-02, 1.83123059e-03],
       [6.02571666e-01, 3.02456111e-01, 9.49721932e-02],
       [8.69527817e-01, 1.23794273e-01, 6.67788368e-03],
       [2.36070961e-01, 3.76435280e-01, 3.87493789e-01],
       [9.11427378e-06, 3.54721420e-03, 9.96443689e-01],
       [6.17461741e-01, 2.95636714e-01, 8.69015455e-02],
       [3.21001244e-05, 6.45795651e-03, 9.93509948e-01],
       [8.43355954e-01, 1.46249801e-01, 1.03941709e-02],
       [8.32596868e-07, 9.63730214e-04, 9.99035478e-01],
       [3.14729587e-05, 6.23638229e-03, 9.93732035e-01],
       [8.83979559e-01, 1.10997006e-01, 5.02337515e-03],
       [9.05089259e-01, 9.18260589e-02, 3.08467797e-03],
       [9.04042125e-01, 9.27898511e-02, 3.16800689e-03],
       [2.05563288e-06, 1.66542723e-03, 9.98332560e-01],
       [7.95934081e-01, 1.84414446e-01, 1.96514875e-02],
       [6.18153581e-06, 2.65623839e-03, 9.97337520e-01],
       [8.80159855e-01, 1.14406087e-01, 5.43410564e-03],
       [9.57348704e-01, 4.22091223e-02, 4.42270102e-04],
       [9.30163920e-01, 6.83722794e-02, 1.46379066e-03],
       [7.91327894e-01, 1.87940165e-01, 2.07319986e-02],
       [9.39530790e-01, 5.94375059e-02, 1.03170436e-03],
       [3.42257663e-05, 6.28575962e-03, 9.93680000e-01],
       [5.58822148e-06, 2.59928894e-03, 9.97395158e-01],
       [9.42154706e-01, 5.69189340e-02, 9.26342967e-04],
       [8.34817767e-01, 1.53366759e-01, 1.18154734e-02],
       [8.32254291e-01, 1.55482963e-01, 1.22628035e-02],
       [9.97120893e-08, 3.29340692e-04, 9.99670506e-01],
       [4.43759859e-07, 7.10788940e-04, 9.99288678e-01],
       [8.72944838e-06, 3.15523962e-03, 9.96836066e-01],
       [7.86347628e-01, 1.91848874e-01, 2.18034014e-02],
       [8.88441622e-01, 1.06991127e-01, 4.56729718e-03],
       [2.36376991e-06, 1.63114886e-03, 9.98366535e-01],
       [4.71176356e-01, 3.48077238e-01, 1.80746391e-01],
       [2.46430318e-07, 5.22297109e-04, 9.99477446e-01],
       [2.50297457e-01, 3.73947531e-01, 3.75754982e-01],
       [4.27015766e-06, 2.47475295e-03, 9.97520983e-01],
       [9.11636770e-01, 8.57703760e-02, 2.59290473e-03],
       [1.27986848e-01, 3.16843331e-01, 5.55169880e-01],
       [8.65440905e-01, 1.27362967e-01, 7.19607482e-03],
       [2.15193359e-05, 5.32143749e-03, 9.94657099e-01],
       [8.76099885e-01, 1.18008763e-01, 5.89146698e-03],
       [8.78416777e-01, 1.15955435e-01, 5.62782073e-03],
       [3.77533078e-01, 3.78268093e-01, 2.44198844e-01],
       [9.40516293e-01, 5.84923476e-02, 9.91345965e-04],
       [4.02112867e-08, 2.08561469e-04, 9.99791443e-01],
       [9.51270759e-01, 4.81182188e-02, 6.10947551e-04],
       [1.71243046e-05, 4.71505336e-03, 9.95267808e-01],
       [7.30476268e-06, 3.13934614e-03, 9.96853411e-01],
       [9.01208758e-01, 9.53911617e-02, 3.40005080e-03],
       [6.45645832e-06, 2.97371531e-03, 9.97019827e-01],
       [9.19850588e-01, 7.81037584e-02, 2.04563607e-03],
       [9.50397134e-01, 4.89649773e-02, 6.37885416e-04]], dtype=float32)

In [14]:
### logit false
inputs_logit_false = keras.Input(shape=(X_train_scaled.shape[1],))
x_logit_false = layers.Dense(7, activation='relu')(inputs_logit_false)
x_logit_false = layers.Dense(5, activation='relu')(x_logit_false)
x_logit_false = layers.Dense(3, activation='relu')(x_logit_false)
outputs_logit_false = layers.Dense(3, activation='softmax')(x_logit_false)
model_logit_false = keras.Model(inputs=inputs_logit_false, outputs=outputs_logit_false, name="penguin_model_scaled")

model_logit_false.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_false = model_logit_false.fit(
    X_train_scaled,
    y_train,
    batch_size=64,
    epochs=100,
    validation_data=(X_val_scaled, y_val)
)

scores = model_logit_false.evaluate(X_val_scaled, y_val, verbose=2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.1692 - loss: 1.1998 - val_accuracy: 0.1791 - val_loss: 1.1774
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.1805 - loss: 1.1644 - val_accuracy: 0.1791 - val_loss: 1.1524
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1805 - loss: 1.1418 - val_accuracy: 0.1791 - val_loss: 1.1321
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1729 - loss: 1.1232 - val_accuracy: 0.1791 - val_loss: 1.1162
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1617 - loss: 1.1084 - val_accuracy: 0.1642 - val_loss: 1.1002
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1429 - loss: 1.0935 - val_accuracy: 0.1791 - val_loss: 1.0875
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1391 - loss: 1.0821 - val_accuracy: 0.1791 - val_loss: 1.0746
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1617 - loss: 1.0704 - val_accuracy: 0.2090 - val_loss: 1.0643
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1955 - loss: 1.0602 - val_accuracy: 0.2537 - val_loss: 1.0526
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.2632 - loss: 1.0490 - val_accuracy: 0.3284 - val_loss: 1.0417
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3421 - loss: 1.0387 - val_accuracy: 0.2985 - val_loss: 1.0309
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4023 - loss: 1.0283 - val_accuracy: 0.3731 - val_loss: 1.0206
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4812 - loss: 1.0187 - val_accuracy: 0.3881 - val_loss: 1.0110
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5263 - loss: 1.0092 - val_accuracy: 0.4179 - val_loss: 1.0015
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5940 - loss: 0.9999 - val_accuracy: 0.4328 - val_loss: 0.9937
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5940 - loss: 0.9914 - val_accuracy: 0.4328 - val_loss: 0.9841
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6353 - loss: 0.9821 - val_accuracy: 0.5224 - val_loss: 0.9755
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6880 - loss: 0.9731 - val_accuracy: 0.5970 - val_loss: 0.9678
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7105 - loss: 0.9642 - val_accuracy: 0.6418 - val_loss: 0.9584
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7444 - loss: 0.9546 - val_accuracy: 0.6418 - val_loss: 0.9495
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7444 - loss: 0.9450 - val_accuracy: 0.6269 - val_loss: 0.9406
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7556 - loss: 0.9357 - val_accuracy: 0.6567 - val_loss: 0.9307
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7782 - loss: 0.9258 - val_accuracy: 0.6866 - val_loss: 0.9215
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8008 - loss: 0.9155 - val_accuracy: 0.7164 - val_loss: 0.9117
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8045 - loss: 0.9050 - val_accuracy: 0.7313 - val_loss: 0.9011
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8158 - loss: 0.8942 - val_accuracy: 0.7612 - val_loss: 0.8904
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8158 - loss: 0.8833 - val_accuracy: 0.7612 - val_loss: 0.8804
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8158 - loss: 0.8723 - val_accuracy: 0.7612 - val_loss: 0.8698
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8158 - loss: 0.8610 - val_accuracy: 0.7612 - val_loss: 0.8596
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8158 - loss: 0.8499 - val_accuracy: 0.7612 - val_loss: 0.8478
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8195 - loss: 0.8383 - val_accuracy: 0.7612 - val_loss: 0.8376
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8195 - loss: 0.8267 - val_accuracy: 0.7761 - val_loss: 0.8261
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8195 - loss: 0.8150 - val_accuracy: 0.7761 - val_loss: 0.8139
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8195 - loss: 0.8035 - val_accuracy: 0.7761 - val_loss: 0.8028
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8195 - loss: 0.7914 - val_accuracy: 0.7761 - val_loss: 0.7914
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8195 - loss: 0.7791 - val_accuracy: 0.7761 - val_loss: 0.7796
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8195 - loss: 0.7672 - val_accuracy: 0.7761 - val_loss: 0.7680
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8195 - loss: 0.7546 - val_accuracy: 0.7761 - val_loss: 0.7561
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8195 - loss: 0.7418 - val_accuracy: 0.7910 - val_loss: 0.7438
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8195 - loss: 0.7287 - val_accuracy: 0.8060 - val_loss: 0.7316
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8195 - loss: 0.7165 - val_accuracy: 0.8060 - val_loss: 0.7188
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8195 - loss: 0.7033 - val_accuracy: 0.8060 - val_loss: 0.7070
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8195 - loss: 0.6901 - val_accuracy: 0.8060 - val_loss: 0.6943
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8195 - loss: 0.6768 - val_accuracy: 0.8060 - val_loss: 0.6821
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8195 - loss: 0.6633 - val_accuracy: 0.8209 - val_loss: 0.6701
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8233 - loss: 0.6501 - val_accuracy: 0.8209 - val_loss: 0.6593
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8233 - loss: 0.6379 - val_accuracy: 0.8060 - val_loss: 0.6468
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8233 - loss: 0.6243 - val_accuracy: 0.8209 - val_loss: 0.6345
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8233 - loss: 0.6112 - val_accuracy: 0.8209 - val_loss: 0.6231
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8233 - loss: 0.5985 - val_accuracy: 0.8209 - val_loss: 0.6112
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8233 - loss: 0.5854 - val_accuracy: 0.8209 - val_loss: 0.5996
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8233 - loss: 0.5727 - val_accuracy: 0.8209 - val_loss: 0.5872
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8233 - loss: 0.5598 - val_accuracy: 0.8209 - val_loss: 0.5758
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8233 - loss: 0.5480 - val_accuracy: 0.8209 - val_loss: 0.5642
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8233 - loss: 0.5353 - val_accuracy: 0.8209 - val_loss: 0.5529
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8233 - loss: 0.5228 - val_accuracy: 0.8209 - val_loss: 0.5416
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8308 - loss: 0.5098 - val_accuracy: 0.8209 - val_loss: 0.5300
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8346 - loss: 0.4974 - val_accuracy: 0.8209 - val_loss: 0.5178
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8346 - loss: 0.4843 - val_accuracy: 0.8209 - val_loss: 0.5063
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8346 - loss: 0.4720 - val_accuracy: 0.8209 - val_loss: 0.4948
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8346 - loss: 0.4606 - val_accuracy: 0.8209 - val_loss: 0.4839
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8383 - loss: 0.4486 - val_accuracy: 0.8209 - val_loss: 0.4734
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8383 - loss: 0.4372 - val_accuracy: 0.8209 - val_loss: 0.4629
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8383 - loss: 0.4261 - val_accuracy: 0.8209 - val_loss: 0.4519
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8421 - loss: 0.4154 - val_accuracy: 0.8209 - val_loss: 0.4409
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8534 - loss: 0.4050 - val_accuracy: 0.8209 - val_loss: 0.4306
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8534 - loss: 0.3949 - val_accuracy: 0.8209 - val_loss: 0.4213
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8534 - loss: 0.3848 - val_accuracy: 0.8209 - val_loss: 0.4121
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8571 - loss: 0.3751 - val_accuracy: 0.8209 - val_loss: 0.4033
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8609 - loss: 0.3659 - val_accuracy: 0.8209 - val_loss: 0.3941
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8609 - loss: 0.3564 - val_accuracy: 0.8209 - val_loss: 0.3850
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8647 - loss: 0.3472 - val_accuracy: 0.8209 - val_loss: 0.3759
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8759 - loss: 0.3378 - val_accuracy: 0.8209 - val_loss: 0.3678
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8835 - loss: 0.3290 - val_accuracy: 0.8209 - val_loss: 0.3603
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8835 - loss: 0.3210 - val_accuracy: 0.8209 - val_loss: 0.3514
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8872 - loss: 0.3124 - val_accuracy: 0.8209 - val_loss: 0.3443
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8872 - loss: 0.3049 - val_accuracy: 0.8209 - val_loss: 0.3362
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8947 - loss: 0.2968 - val_accuracy: 0.8209 - val_loss: 0.3294
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8947 - loss: 0.2901 - val_accuracy: 0.8209 - val_loss: 0.3227
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9023 - loss: 0.2826 - val_accuracy: 0.8507 - val_loss: 0.3151
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9060 - loss: 0.2748 - val_accuracy: 0.8507 - val_loss: 0.3081
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9060 - loss: 0.2679 - val_accuracy: 0.8657 - val_loss: 0.3014
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9173 - loss: 0.2612 - val_accuracy: 0.8657 - val_loss: 0.2952
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9248 - loss: 0.2546 - val_accuracy: 0.8657 - val_loss: 0.2895
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9248 - loss: 0.2482 - val_accuracy: 0.8657 - val_loss: 0.2837
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9286 - loss: 0.2418 - val_accuracy: 0.8806 - val_loss: 0.2782
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9286 - loss: 0.2350 - val_accuracy: 0.8806 - val_loss: 0.2737
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9286 - loss: 0.2290 - val_accuracy: 0.8806 - val_loss: 0.2671
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9286 - loss: 0.2229 - val_accuracy: 0.9104 - val_loss: 0.2601
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9398 - loss: 0.2172 - val_accuracy: 0.9254 - val_loss: 0.2558
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9511 - loss: 0.2113 - val_accuracy: 0.9254 - val_loss: 0.2511
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9511 - loss: 0.2059 - val_accuracy: 0.9254 - val_loss: 0.2448
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9511 - loss: 0.2006 - val_accuracy: 0.9403 - val_loss: 0.2386
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9662 - loss: 0.1953 - val_accuracy: 0.9403 - val_loss: 0.2331
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9662 - loss: 0.1901 - val_accuracy: 0.9403 - val_loss: 0.2290
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9662 - loss: 0.1850 - val_accuracy: 0.9403 - val_loss: 0.2237
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9662 - loss: 0.1803 - val_accuracy: 0.9403 - val_loss: 0.2199
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9662 - loss: 0.1751 - val_accuracy: 0.9403 - val_loss: 0.2153
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9662 - loss: 0.1702 - val_accuracy: 0.9403 - val_loss: 0.2112
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9699 - loss: 0.1654 - val_accuracy: 0.9403 - val_loss: 0.2063
3/3 - 0s - 11ms/step - accuracy: 0.9403 - loss: 0.2063

In [15]:
model_logit_false.predict(X_val_scaled)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

array([[2.24977164e-04, 2.95091216e-02, 9.70265985e-01],
       [9.19167697e-02, 7.39591897e-01, 1.68491304e-01],
       [5.89278519e-01, 4.03122246e-01, 7.59924063e-03],
       [7.45050420e-05, 2.01248080e-02, 9.79800701e-01],
       [6.48830837e-06, 8.58683325e-03, 9.91406679e-01],
       [5.85901216e-05, 1.85121354e-02, 9.81429279e-01],
       [7.34783828e-01, 2.63424069e-01, 1.79207453e-03],
       [8.40479255e-01, 1.58723831e-01, 7.96976208e-04],
       [8.95970285e-01, 1.02495313e-01, 1.53444335e-03],
       [5.50839904e-05, 1.81190372e-02, 9.81825829e-01],
       [3.00312757e-01, 6.52130008e-01, 4.75572422e-02],
       [9.75848675e-01, 2.36458052e-02, 5.05421020e-04],
       [9.68969703e-01, 3.08617484e-02, 1.68518949e-04],
       [6.52961791e-01, 3.44072431e-01, 2.96575110e-03],
       [3.79219443e-01, 6.01239443e-01, 1.95411220e-02],
       [9.12133217e-01, 8.77346843e-02, 1.32135407e-04],
       [2.81895071e-01, 6.96298361e-01, 2.18065437e-02],
       [8.52831662e-01, 1.46759570e-01, 4.08805179e-04],
       [4.46941942e-01, 5.42327464e-01, 1.07305851e-02],
       [1.32167409e-03, 5.40933721e-02, 9.44584966e-01],
       [3.95775318e-01, 5.90902269e-01, 1.33224437e-02],
       [4.78824181e-03, 8.31946880e-02, 9.12017047e-01],
       [7.85461962e-01, 2.13377804e-01, 1.16025808e-03],
       [2.90694414e-04, 3.22351716e-02, 9.67474103e-01],
       [6.38538552e-03, 1.05973072e-01, 8.87641490e-01],
       [8.78554404e-01, 1.20763175e-01, 6.82456943e-04],
       [9.72343445e-01, 2.72467267e-02, 4.09828062e-04],
       [8.61033261e-01, 1.38091847e-01, 8.74899444e-04],
       [1.52330298e-03, 5.67543618e-02, 9.41722274e-01],
       [6.64311469e-01, 3.33199888e-01, 2.48864735e-03],
       [4.97400120e-04, 3.87694314e-02, 9.60733175e-01],
       [9.73741770e-01, 2.53780931e-02, 8.80065607e-04],
       [9.73728180e-01, 2.62589417e-02, 1.28884558e-05],
       [9.66911077e-01, 3.30253467e-02, 6.36608456e-05],
       [6.36242628e-01, 3.58603835e-01, 5.15348138e-03],
       [9.92582917e-01, 7.34805269e-03, 6.89503941e-05],
       [1.98556995e-03, 6.26285225e-02, 9.35385883e-01],
       [1.67123938e-03, 5.85581176e-02, 9.39770639e-01],
       [9.89183307e-01, 1.07837804e-02, 3.29147260e-05],
       [6.85472906e-01, 3.11482757e-01, 3.04435287e-03],
       [6.48949027e-01, 3.44227642e-01, 6.82326918e-03],
       [1.97040034e-04, 2.81886123e-02, 9.71614420e-01],
       [2.65348790e-04, 3.12376712e-02, 9.68497038e-01],
       [2.21446250e-03, 6.43738806e-02, 9.33411658e-01],
       [5.66894770e-01, 4.28594202e-01, 4.51108394e-03],
       [9.26910341e-01, 7.16344044e-02, 1.45527534e-03],
       [1.53234854e-04, 2.58416515e-02, 9.74005103e-01],
       [1.50060147e-01, 7.49004006e-01, 1.00935809e-01],
       [3.44110624e-04, 3.41622494e-02, 9.65493560e-01],
       [3.35878909e-01, 6.08683050e-01, 5.54380119e-02],
       [1.60250789e-03, 5.77341877e-02, 9.40663218e-01],
       [9.07514155e-01, 9.23292637e-02, 1.56534225e-04],
       [3.49750936e-01, 6.27681613e-01, 2.25675050e-02],
       [8.85108352e-01, 1.11818194e-01, 3.07353586e-03],
       [4.95936070e-03, 8.41614455e-02, 9.10879076e-01],
       [9.51656222e-01, 4.72522564e-02, 1.09145627e-03],
       [8.68429065e-01, 1.31219968e-01, 3.50970222e-04],
       [4.00505096e-01, 5.77901185e-01, 2.15937179e-02],
       [9.88558531e-01, 1.13858860e-02, 5.56382402e-05],
       [4.21502809e-05, 1.65074933e-02, 9.83450294e-01],
       [9.74312246e-01, 2.56719328e-02, 1.58334733e-05],
       [2.67376285e-03, 6.85680509e-02, 9.28758204e-01],
       [1.79248070e-03, 5.99570125e-02, 9.38250542e-01],
       [8.96341681e-01, 1.03339359e-01, 3.18942621e-04],
       [2.02317373e-03, 6.24501146e-02, 9.35526729e-01],
       [9.61477578e-01, 3.81660089e-02, 3.56460747e-04],
       [9.61572230e-01, 3.84086408e-02, 1.91928375e-05]], dtype=float32)

In [16]:
penguins['species']

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: str

In [17]:
### training data
penguins_y

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)